interface DefaultCategory {
  name: string;
  icon: string;
  color: string;
}

const CATEGORIES: Record<string, DefaultCategory[]> = {
  en: [
    { name: 'Food & Dining', icon: '🍔', color: '#FF6B6B' },
    { name: 'Groceries', icon: '🛒', color: '#4ECDC4' },
    { name: 'Transport', icon: '🚗', color: '#45B7D1' },
    { name: 'Shopping', icon: '🛍️', color: '#96CEB4' },
    { name: 'Entertainment', icon: '🎬', color: '#FFEAA7' },
    { name: 'Bills & Utilities', icon: '💡', color: '#DFE6E9' },
    { name: 'Health', icon: '💊', color: '#A29BFE' },
    { name: 'Education', icon: '📚', color: '#6C5CE7' },
    { name: 'Clothing', icon: '👕', color: '#FD79A8' },
    { name: 'Gifts', icon: '🎁', color: '#E17055' },
    { name: 'Travel', icon: '✈️', color: '#00B894' },
    { name: 'Subscriptions', icon: '📱', color: '#0984E3' },
    { name: 'Salary', icon: '💰', color: '#00B894' },
    { name: 'Freelance', icon: '💻', color: '#6C5CE7' },
    { name: 'Other', icon: '📦', color: '#636E72' },
  ],
  ru: [
    { name: 'Еда и рестораны', icon: '🍔', color: '#FF6B6B' },
    { name: 'Продукты', icon: '🛒', color: '#4ECDC4' },
    { name: 'Транспорт', icon: '🚗', color: '#45B7D1' },
    { name: 'Покупки', icon: '🛍️', color: '#96CEB4' },
    { name: 'Развлечения', icon: '🎬', color: '#FFEAA7' },
    { name: 'Счета и коммунальные', icon: '💡', color: '#DFE6E9' },
    { name: 'Здоровье', icon: '💊', color: '#A29BFE' },
    { name: 'Образование', icon: '📚', color: '#6C5CE7' },
    { name: 'Одежда', icon: '👕', color: '#FD79A8' },
    { name: 'Подарки', icon: '🎁', color: '#E17055' },
    { name: 'Путешествия', icon: '✈️', color: '#00B894' },
    { name: 'Подписки', icon: '📱', color: '#0984E3' },
    { name: 'Зарплата', icon: '💰', color: '#00B894' },
    { name: 'Фриланс', icon: '💻', color: '#6C5CE7' },
    { name: 'Другое', icon: '📦', color: '#636E72' },
  ],
  ua: [
    { name: 'Їжа та ресторани', icon: '🍔', color: '#FF6B6B' },
    { name: 'Продукти', icon: '🛒', color: '#4ECDC4' },
    { name: 'Транспорт', icon: '🚗', color: '#45B7D1' },
    { name: 'Покупки', icon: '🛍️', color: '#96CEB4' },
    { name: 'Розваги', icon: '🎬', color: '#FFEAA7' },
    { name: 'Рахунки та комунальні', icon: '💡', color: '#DFE6E9' },
    { name: "Здоров'я", icon: '💊', color: '#A29BFE' },
    { name: 'Освіта', icon: '📚', color: '#6C5CE7' },
    { name: 'Одяг', icon: '👕', color: '#FD79A8' },
    { name: 'Подарунки', icon: '🎁', color: '#E17055' },
    { name: 'Подорожі', icon: '✈️', color: '#00B894' },
    { name: 'Підписки', icon: '📱', color: '#0984E3' },
    { name: 'Зарплата', icon: '💰', color: '#00B894' },
    { name: 'Фріланс', icon: '💻', color: '#6C5CE7' },
    { name: 'Інше', icon: '📦', color: '#636E72' },
  ],
  pl: [
    { name: 'Jedzenie i restauracje', icon: '🍔', color: '#FF6B6B' },
    { name: 'Zakupy spożywcze', icon: '🛒', color: '#4ECDC4' },
    { name: 'Transport', icon: '🚗', color: '#45B7D1' },
    { name: 'Zakupy', icon: '🛍️', color: '#96CEB4' },
    { name: 'Rozrywka', icon: '🎬', color: '#FFEAA7' },
    { name: 'Rachunki', icon: '💡', color: '#DFE6E9' },
    { name: 'Zdrowie', icon: '💊', color: '#A29BFE' },
    { name: 'Edukacja', icon: '📚', color: '#6C5CE7' },
    { name: 'Ubrania', icon: '👕', color: '#FD79A8' },
    { name: 'Prezenty', icon: '🎁', color: '#E17055' },
    { name: 'Podróże', icon: '✈️', color: '#00B894' },
    { name: 'Subskrypcje', icon: '📱', color: '#0984E3' },
    { name: 'Wynagrodzenie', icon: '💰', color: '#00B894' },
    { name: 'Freelance', icon: '💻', color: '#6C5CE7' },
    { name: 'Inne', icon: '📦', color: '#636E72' },
  ],
  de: [
    { name: 'Essen & Restaurants', icon: '🍔', color: '#FF6B6B' },
    { name: 'Lebensmittel', icon: '🛒', color: '#4ECDC4' },
    { name: 'Transport', icon: '🚗', color: '#45B7D1' },
    { name: 'Einkaufen', icon: '🛍️', color: '#96CEB4' },
    { name: 'Unterhaltung', icon: '🎬', color: '#FFEAA7' },
    { name: 'Rechnungen', icon: '💡', color: '#DFE6E9' },
    { name: 'Gesundheit', icon: '💊', color: '#A29BFE' },
    { name: 'Bildung', icon: '📚', color: '#6C5CE7' },
    { name: 'Kleidung', icon: '👕', color: '#FD79A8' },
    { name: 'Geschenke', icon: '🎁', color: '#E17055' },
    { name: 'Reisen', icon: '✈️', color: '#00B894' },
    { name: 'Abonnements', icon: '📱', color: '#0984E3' },
    { name: 'Gehalt', icon: '💰', color: '#00B894' },
    { name: 'Freelance', icon: '💻', color: '#6C5CE7' },
    { name: 'Sonstiges', icon: '📦', color: '#636E72' },
  ],
  es: [
    { name: 'Comida y restaurantes', icon: '🍔', color: '#FF6B6B' },
    { name: 'Supermercado', icon: '🛒', color: '#4ECDC4' },
    { name: 'Transporte', icon: '🚗', color: '#45B7D1' },
    { name: 'Compras', icon: '🛍️', color: '#96CEB4' },
    { name: 'Entretenimiento', icon: '🎬', color: '#FFEAA7' },
    { name: 'Facturas', icon: '💡', color: '#DFE6E9' },
    { name: 'Salud', icon: '💊', color: '#A29BFE' },
    { name: 'Educación', icon: '📚', color: '#6C5CE7' },
    { name: 'Ropa', icon: '👕', color: '#FD79A8' },
    { name: 'Regalos', icon: '🎁', color: '#E17055' },
    { name: 'Viajes', icon: '✈️', color: '#00B894' },
    { name: 'Suscripciones', icon: '📱', color: '#0984E3' },
    { name: 'Salario', icon: '💰', color: '#00B894' },
    { name: 'Freelance', icon: '💻', color: '#6C5CE7' },
    { name: 'Otros', icon: '📦', color: '#636E72' },
  ],
  fr: [
    { name: 'Repas et restaurants', icon: '🍔', color: '#FF6B6B' },
    { name: 'Courses', icon: '🛒', color: '#4ECDC4' },
    { name: 'Transport', icon: '🚗', color: '#45B7D1' },
    { name: 'Shopping', icon: '🛍️', color: '#96CEB4' },
    { name: 'Divertissement', icon: '🎬', color: '#FFEAA7' },
    { name: 'Factures', icon: '💡', color: '#DFE6E9' },
    { name: 'Santé', icon: '💊', color: '#A29BFE' },
    { name: 'Éducation', icon: '📚', color: '#6C5CE7' },
    { name: 'Vêtements', icon: '👕', color: '#FD79A8' },
    { name: 'Cadeaux', icon: '🎁', color: '#E17055' },
    { name: 'Voyages', icon: '✈️', color: '#00B894' },
    { name: 'Abonnements', icon: '📱', color: '#0984E3' },
    { name: 'Salaire', icon: '💰', color: '#00B894' },
    { name: 'Freelance', icon: '💻', color: '#6C5CE7' },
    { name: 'Autres', icon: '📦', color: '#636E72' },
  ],
  be: [
    { name: 'Ежа і рэстараны', icon: '🍔', color: '#FF6B6B' },
    { name: 'Прадукты', icon: '🛒', color: '#4ECDC4' },
    { name: 'Транспарт', icon: '🚗', color: '#45B7D1' },
    { name: 'Пакупкі', icon: '🛍️', color: '#96CEB4' },
    { name: 'Забавы', icon: '🎬', color: '#FFEAA7' },
    { name: 'Рахункі і камунальныя', icon: '💡', color: '#DFE6E9' },
    { name: "Здароў'е", icon: '💊', color: '#A29BFE' },
    { name: 'Адукацыя', icon: '📚', color: '#6C5CE7' },
    { name: 'Адзенне', icon: '👕', color: '#FD79A8' },
    { name: 'Падарункі', icon: '🎁', color: '#E17055' },
    { name: 'Падарожжы', icon: '✈️', color: '#00B894' },
    { name: 'Падпіскі', icon: '📱', color: '#0984E3' },
    { name: 'Зарплата', icon: '💰', color: '#00B894' },
    { name: 'Фрыланс', icon: '💻', color: '#6C5CE7' },
    { name: 'Іншае', icon: '📦', color: '#636E72' },
  ],
};

export function getDefaultCategories(language: string): DefaultCategory[] {
  return CATEGORIES[language] || CATEGORIES.en;
}
